[package]
name = "informatik-game-bevy"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.2"
rand = "0.9.2"

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
